@REM This file was automatically generated by alyxlib.
@REM Run this file before uploading your addon to the workshop, then follow window instructions after uploading.
@echo off


IF NOT EXIST "C:\Program Files (x86)\Steam\steamapps\common\Half-Life Alyx\content\hlvr_addons\alyxlib" (
echo AlyxLib folder wasn't found, cannot perform this batch file! Please rerun alyxlib.py to setup correctly...
PAUSE
EXIT
)

rmdir "C:\Program Files (x86)\Steam\steamapps\common\Half-Life Alyx\content\hlvr_addons\partial_clip_storage\scripts\vscripts\alyxlib"
del "C:\Program Files (x86)\Steam\steamapps\common\Half-Life Alyx\content\hlvr_addons\partial_clip_storage\scripts\vlua_globals.lua"
rmdir "C:\Program Files (x86)\Steam\steamapps\common\Half-Life Alyx\content\hlvr_addons\partial_clip_storage\scripts\vscripts\game"

echo Symlinks have been removed, continue after uploading to workshop.
PAUSE
echo.

mklink /d "C:\Program Files (x86)\Steam\steamapps\common\Half-Life Alyx\content\hlvr_addons\partial_clip_storage\scripts\vscripts\alyxlib" "C:\Program Files (x86)\Steam\steamapps\common\Half-Life Alyx\content\hlvr_addons\alyxlib\scripts\vscripts\alyxlib"
echo.
mklink "C:\Program Files (x86)\Steam\steamapps\common\Half-Life Alyx\content\hlvr_addons\partial_clip_storage\scripts\vlua_globals.lua" "C:\Program Files (x86)\Steam\steamapps\common\Half-Life Alyx\content\hlvr_addons\alyxlib\scripts\vlua_globals.lua"
echo.
mklink /d "C:\Program Files (x86)\Steam\steamapps\common\Half-Life Alyx\content\hlvr_addons\partial_clip_storage\scripts\vscripts\game" "C:\Program Files (x86)\Steam\steamapps\common\Half-Life Alyx\content\hlvr_addons\alyxlib\scripts\vscripts\game"
echo.

echo Symlinks reinstated! This window can now be closed.
PAUSE
